# If you wish to make install, point this at the relevant place
INSTALLDIR=/usr/local/games/jugglemaster/

# For jmdlx to export MPEGs, you need ffmpeg.
# If you have it, point this at the directory you built it in,
#  and set HAVE_FFMPEG to 1. Tested with 0.4.9-pre1
FFMPEG_PREFIX=/tmp/chunky/ffmpeg
HAVE_FFMPEG=0


# You shouldn't have to edit anything below this line

VERSION=0.4
DEBUG=0
