# This file auto-generated by Palm OS Make builder.  Don't modify directly!!!

# This value is unescaped.  Either quote the value or escape special characters when you use it.
ifeq ($(TOOLS_DIR), )
   TOOLS_DIR = D:/programming/Palm OS Developer Suite/PalmOSTools/
endif

# This value is unescaped.  Either quote the value or escape special characters when you use it.
ifeq ($(SDK_LOCATION), )
   SDK_LOCATION = D:/programming/Palm OS Developer Suite/sdk-5r4/
endif

ifeq ($(SDK_VERSION), )
   SDK_VERSION = sdk-5r4
endif

ifeq ($(PROJECT_VERSION), )
   PROJECT_VERSION = 10100
endif

ifeq ($(SDK), )
   SDK = com.palmsource.eclipse.sdk.palmos5
endif

ifeq ($(OS_API), )
   OS_API = 68K
endif

ifeq ($(PROJECT_TYPE), )
   PROJECT_TYPE = appl
endif

